import vue from 'eslint-plugin-vue';

export default [
  {
    files: ['**/*.{js,vue}'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
      parser: 'vue-eslint-parser',
      globals: {
        browser: true,
        node: true,
      },
    },
    plugins: {
      vue,
    },
    rules: {
      'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'warn',
      'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'warn',
      'vue/multi-word-component-names': 'off',
      'vue/attribute-hyphenation': 'error',
      'vue/require-default-prop': 'error',
      'vue/require-prop-types': 'error',
      'vue/script-setup-uses-vars': 'error',
      'vue/no-unused-vars': 'error',
      'vue/no-unused-components': 'error',
      'vue/no-duplicate-attr-inheritance': 'error',
      'vue/no-multiple-template-root': 'error',
      'vue/valid-template-root': 'error',
      'vue/valid-v-for': 'error',
      'vue/valid-v-if': 'error',
      'vue/valid-v-model': 'error',
      'vue/valid-v-on': 'error',
      'vue/valid-v-show': 'error',
      'vue/valid-v-slot': 'error',
      'no-unused-vars': 'error',
      'no-unused-imports': 'error',
      'no-undef': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'prefer-arrow-callback': 'error',
      'arrow-spacing': 'error',
      'brace-style': 'error',
      'comma-dangle': ['error', 'always-multiline'],
      'comma-spacing': 'error',
      'eol-last': 'error',
      'indent': ['error', 2, { 'SwitchCase': 1 }],
      'keyword-spacing': 'error',
      'linebreak-style': ['error', 'unix'],
      'no-mixed-spaces-and-tabs': 'error',
      'no-trailing-spaces': 'error',
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'space-before-blocks': 'error',
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'no-multiple-empty-lines': ['error', { 'max': 1, 'maxBOF': 0, 'maxEOF': 0 }],
    },
  },
];